export const ONE  = () =>({type:'ONE',value:'1'})
export const TWO  = () =>({type:'TWO',value:'2'})
export const PLUS = () => ({type:'PLUS',value:'+'})
export const THREE = () => ({type:'THREE',value:'3'})
export const FOUR = () => ({type:'FOUR',value:'4'})
export const FIVE = () => ({type:'FIVE',value:'5'})
export const SIX = () => ({type:'SIX',value:'6'})
export const SEVEN = () => ({type:'SEVEN',value:'7'})
export const EIGHT = () => ({type:'EIGHT',value:'8'})
export const NINE = () => ({type:'NINE',value:'9'})
export const ZERO = () => ({type:'ZERO',value:'0'})
export const MINUS = () => ({type:'MINUS',value:'-'})
export const DIVIDE = () => ({type:'DIVIDE',value:'/'})
export const MULTIPLY = () => ({type:'MULTIPLY',value:'*'})
export const EQUAL = () => ({type:'EQUAL'});